#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/ez2desk /usr/bin/rustdesk
		
		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop ez2desk || true
			systemctl disable ez2desk || true
			systemctl stop rustdesk || true
			systemctl disable rustdesk || true
			rm /etc/systemd/system/ez2desk.service /usr/lib/systemd/system/ez2desk.service || true
			rm /etc/systemd/system/rustdesk.service /usr/lib/systemd/system/rustdesk.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'ez2desk +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop rustdesk >/dev/null 2>&1 || true
				systemctl --machine=${serverUser}@.host --user stop ez2desk >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/rustdesk.service /usr/lib/systemd/user/ez2desk.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
